language: python

cache: pip


python:
- "3.6"

install:
# Other dependencies here
- pip install pylint
#- pip install pyccl


script:
#- pylint 
- py.test 
- '[ -z "$CHANGED" ] || pylint --disable=C0103,C0301,W0511 --extension-pkg-whitelist=numpy $CHANGED; EXITCODE=$?; if [ $(($EXITCODE&7)) -gt 0 ]; then exit $EXITCODE; fi;'

